In [1]:
import numpy as np
my_array = np.array([[1.5,1.3,7.5],[5.6,7.8,1.2]])
my_array

array([[ 1.5,  1.3,  7.5],
       [ 5.6,  7.8,  1.2]])

In [2]:
np.sort(my_array)

array([[ 1.3,  1.5,  7.5],
       [ 1.2,  5.6,  7.8]])

In [3]:
np.sort(my_array,axis=0)

array([[ 1.5,  1.3,  1.2],
       [ 5.6,  7.8,  7.5]])

In [5]:
my_array

array([[ 1.5,  1.3,  7.5],
       [ 5.6,  7.8,  1.2]])

In [4]:
np.argsort(my_array)

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [6]:
my_array = np.linspace(0,10,10)
my_array

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

In [8]:
values = np.array([2.5,6.5,9.5])

In [9]:
np.searchsorted(my_array,values) #my_array必須已經是排序好，才能用searchsorted

array([3, 6, 9], dtype=int64)

In [10]:
my_array = np.array([[1,0,6],
                     [1,7,0],
                     [2,3,1],
                     [2,4,0]])

In [11]:
my_array

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [13]:
index = np.lexsort([-1*my_array[:,0],my_array[:,2]])
index

array([3, 1, 2, 0], dtype=int64)

In [14]:
my_array = my_array[index]

In [15]:
my_array

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])