### 數組形狀操作

In [1]:
import numpy as np
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
my_array.shape

(10,)

In [3]:
my_array.shape = 2,5

In [4]:
my_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
my_array.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

大小不能改變

In [7]:
my_array.shape=3,4

ValueError: cannot reshape array of size 10 into shape (3,4)

In [15]:
my_array = np.arange(10)
my_array.shape

(10,)

In [16]:
my_array = my_array[np.newaxis,:]
my_array.shape

(1, 10)

In [17]:
my_array = np.arange(10)
my_array.shape

(10,)

In [18]:
my_array = my_array[:,np.newaxis]
my_array.shape

(10, 1)

In [19]:
my_array = my_array[:,np.newaxis,np.newaxis]
my_array.shape

(10, 1, 1, 1)

In [24]:
my_array = my_array.squeeze()
my_array.shape

(10,)

In [25]:
my_array.shape=2,5
my_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
my_array.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [27]:
my_array.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

### 數組的連結

In [28]:
a = np.array([[123,456,678],[3214,456,134]])
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [29]:
b = np.array([[1235,3124,432],[43,13,134]])
b

array([[1235, 3124,  432],
       [  43,   13,  134]])

In [31]:
c = np.concatenate((a,b))
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [32]:
c = np.concatenate((a,b),axis = 1)
c

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [33]:
c.shape

(2, 6)

In [34]:
np.vstack((a,b))

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [35]:
np.hstack((a,b))

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [36]:
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [38]:
a.flatten()

array([ 123,  456,  678, 3214,  456,  134])

In [39]:
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [40]:
a.ravel()

array([ 123,  456,  678, 3214,  456,  134])

In [41]:
a

array([[ 123,  456,  678],
       [3214,  456,  134]])