In [1]:
import numpy as np

In [2]:
x = np.array([5,5])
y = np.array([2,2])

In [3]:
np.multiply(x,y)

array([10, 10])

In [5]:
np.dot(x,y)

20

In [6]:
x.shape

(2,)

In [7]:
y.shape

(2,)

In [8]:
x.shape=2,1

In [9]:
x

array([[5],
       [5]])

In [10]:
np.dot(x,y)

ValueError: shapes (2,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

In [11]:
y.shape=1,2

In [12]:
y

array([[2, 2]])

In [13]:
#http://math1.ck.tp.edu.tw/%E6%9E%97%E4%BF%A1%E5%AE%89/%E5%AD%B8%E8%A1%93%E7%A0%94%E7%A9%B6/%E4%B8%8A%E8%AA%B2%E8%AC%9B%E7%BE%A9/%E7%AC%AC%E4%BA%94%E5%86%8A/3-1%E7%9F%A9%E9%99%A3%E7%9A%84%E9%81%8B%E7%AE%97.pdf
np.dot(x,y)

array([[10, 10],
       [10, 10]])

In [14]:
print(x.shape)
print(y.shape)

(2, 1)
(1, 2)


In [15]:
np.dot(y,x)

array([[20]])

In [17]:
x = np.array([1,1,1])
y = np.array([[1,2,3],[4,5,6]])
x * y

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
x = np.array([1,1,1])
y = np.array([1,1,1])
x == y

array([ True,  True,  True], dtype=bool)

In [19]:
np.logical_and(x,y)

array([ True,  True,  True], dtype=bool)